spring:
  datasource:
    url: jdbc:mysql://121.199.9.8:3306/gulimall_coupon
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-coupon
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 7000